### ISSUE TITLE
Declare tokens.studio TypeScript types

### ISSUE THREAD

**Issue by gsouquet** [tokens-studio/sd-transforms#18]
This repo seems to be taking some shy steps in the TypeScript ecosystem.

I believe there would be quite a bit of value in declaring a typescript type structure to express what is documenting on https://docs.tokens.studio/available-tokens/available-tokens .

Would this repo be the right place to contribute this change?

**Comment by jorenbroekema** [comment]
Hm yeah I have been thinking about this as well, because at the moment in this library, a "design token" is typed as `DesignToken` type from `style-dictionary` library, but this doesn't map 1 to 1 with design tokens as they are created in Tokens Studio.

I believe it would be very useful if we had a type for tokens studio design tokens, where we also have an enum type for the token type based on the available tokens in tokens studio.

@six7 I am guessing such a type already exists somewhere in the tokens studio / figma plugin source code, perhaps it's an idea to export it somewhere so it can be reused here in this library as well as by consumers for their own purposes.
I am not completely sure where that "somewhere" should be, I'm personally not against putting it in this library if we don't have somewhere that makes more sense that's also published as an npm package.

As for my philophy behind Typescript, for what it's worth, it's something like this:

Type safety is an absolute must, both for library maintainers and consumers. However, Typescript compilation step during local development, testing and demoing, has too often proven a massive overhead, along with Typescript patch/minor updates often breaking the types. The main benefit with using `.js` files + JSDoc comments is that the code always runs regardless of a broken type somewhere, and you don't need a mandatory compilation step, thus speeding up development significantly. Yet, you get all the same benefits of full type safety such as maintenance, spotting certain bugs early, self-documentation of public API, etc. Even though the ergonomics of JSDocs may not really match that of writing TS files, it's worth it when considering all the negatives of Typescript files, in my personal opinion.

**Comment by six7** [comment]
There is, we do have those types defined for tokens studio itself. Should we just have a @tokens-studio/types package that exports this and is being used by this package and by the plugin (and by future products)?

**Comment by jorenbroekema** [comment]
Yeah I think that would make sense 👍🏻 I don't mind doing it, if you can point me to the type definition in a DM or something :)

**Comment by six7** [comment]
This should be the entry point for those: https://github.com/tokens-studio/figma-plugin/blob/main/src/types/tokens/SingleToken.ts

**Comment by Jasperrr91** [comment]
For a new project, I'm looking into using some of these transformers; and I am more than willing to contribute to this project. We have some additional generic transformers and we could always help with unit testing and proper project set up and the likes. The latter is what I'm currently running into with the project as is. TypeScript is the first thing that I would expect here.

I've read your reasoning

> However, Typescript compilation step during local development, testing and demoing, has too often proven a massive overhead, along with Typescript patch/minor updates often breaking the types.

I have maintained a large design system in TypeScript for a year and we rarely to never had issues with TypeScript patch/minor updates. Furthermore, the overhead is not that big. With a good setup, you don't need to compile during local development and testing. You will of course have to when publishing your release files and this does add some time, but with a library of this size we are talking about mere seconds. Micro-optimalisations.

> The main benefit with using .js files + JSDoc comments is that the code always runs regardless of a broken type somewhere

This is the sole reason you want type checking, to make sure your code runs only when the input and output is as expected. Of course there's still ways to bypass this check with actual TS but this is never really advised.

Add in the mix that writing the JSDocs probably takes up more time than the few seconds TS compilation during release adds, and the fact that JSDocs needs extra extensions and such installed for proper support and full type safety; and TS is just the better option.

I'd be more than willing to submit a PR with a TS rewrite but of course only if I'm sure that it won't be disregarded anyways..

**Comment by jorenbroekema** [comment]
> I have maintained a large design system in TypeScript for a year and we rarely to never had issues with TypeScript patch/minor updates. Furthermore, the overhead is not that big.

I understand. My experience is different, and that perhaps has to do with my usage of JavaScript Mixins and the TypeScript inheritance hell that you get when using this pattern, this repository fortunately doesn't require such patterns.

> This is the sole reason you want type checking, to make sure your code runs only when the input and output is as expected. Of course there's still ways to bypass this check with actual TS but this is never really advised.

If I'm making quick refactors or playing around with some code, experimenting, doing small POCs, I don't want to deal with not seeing results until I fix types. It's a waste of time. JavaScript is a nimble language, which is why I am fast and productive writing it, TypeScript compilation restrictions makes it less nimble.

> Add in the mix that writing the JSDocs probably takes up more time than the few seconds TS compilation during release adds, and the fact that JSDocs needs extra extensions and such installed for proper support and full type safety; and TS is just the better option.
> 
> I'd be more than willing to submit a PR with a TS rewrite but of course only if I'm sure that it won't be disregarded anyways..

Agree to disagree. This simply hasn't been my experience trying both methods extensively in many different projects. You don't need extra extensions. The autocomplete/suggest and typescript language server in VS Code as well as other editors, works just fine with TS files as JSDocs comments in JS files. It has worked great since at least the introduction of the checkJs/allowJs TS options, before that I'm not sure.

I appreciate your perspective on this though, and I understand the argument that if you want to invite collaboration and contributions, which is quite crucial to this particular project, it is wiser to go with the more popular choice, even if it isn't a personal preference. Lowering barrier to entry for collaboration is the most important thing here, more important than me sticking to my personal preference.

Therefore, I've raised a draft PR to switch the project to TypeScript.

**Comment by jorenbroekema** [comment]
Fixed, we have a package for our shared types now! https://github.com/tokens-studio/types
