### ISSUE TITLE
Use of attribute/cti

### ISSUE THREAD

**Issue by thomasmattheussen** [tokens-studio/sd-transforms#33]
Hi,

I was just wondering why you're using the attribute/cti transform?

Since Tokens Studio adds a `type` to every token, we decided to no longer use this transform as we can write all our matchers by using the `type` prop instead of using inferred types from the token name.

**Comment by jorenbroekema** [comment]
You need some kind of name transformer to ensure you don't get token collisions in the final output.

```json
{
  "color": {
    "red": {
      "accent": {
        "value": "#FF0000",
        "type": "color"
      }
    },
    "black": {
      "accent": {
        "value": "#000000",
        "type": "color"
      }
    },
    "white": {
      "accent": {
        "value": "#FFFFFF",
        "type": "color"
      }
    }
  }  
}
```
The above, without such a transformer, gives you a collision between the three tokens, because without a name transformer, the token names would be `"accent"` for all 3 of them. 

It's a name transformer like `name/cti/kebab` that takes the parent keys and combines them to become:
- `"color-red-accent"`
- `"color-black-accent"`
- `"color-white-accent"`

Here's an example to demonstrate this https://www.style-dictionary-play.dev/#project=pVHLcoMwDPyVjHtjPJhzPiDn3kOmI4xpXBybsU3aToZ/r4V5GG5pfAFJK61W+yDcKGNZBU7k3rRCu/zLGU2O5FHqw6GM9ZIcD2OMGSvqJMYMcC603yQxfQfVC8yW5O10KsIrCU0B/reb6hPLXBziz0BnzkoBb59nLYqXWL+v0ov/aMX3LCt+hoDUA6EBoxv5ubPCmd7ycch53jDLWJb6FsdeaGzoFPjG2Jvb+Med22nyFrRbgOd0bQ03wbiXrBUVVOvWF7q2d1Y08ieKc3WiO/jWS1W/g7/G6hiysADboBqpxJ46uS5CauG81OAlasRRH3ewEqrQmI+C6BaPasBPBw98C3qVsJw+qEk9QAeGPw==

You should see proper style-dictionary output. Now remove the transform in the sd.config.json and note the console warnings you get, and the faulty CSS output (three tokens with the same names).

I hope my explanation helps :)

**Comment by thomasmattheussen** [comment]
That explains the use `name/cti/kebab`, but I was referring to `attribute/cti`. Or am I missing something here? 😅

**Comment by jorenbroekema** [comment]
Oh true, I hadn't really noticed that one, this is only for putting attributes meta info, but it's not used for creating the CTI name, so it can be removed. 

Technically a breaking change, but I'm open to a PR for this to remove that transform from registerTransforms, we'll have to release it as a new minor version.
