### ISSUE TITLE
Support $ reference syntax

### ISSUE THREAD

**Issue by fudris** [tokens-studio/sd-transforms#67]
It seems that references written in Tokens studio within { } work well during translation, but not the ones written with a $.

**Comment by jorenbroekema** [comment]
We could potentially support this now with the preprocessors hook that style-dictionary exposes since v4 prerelease, looping over all tokens values and find+replace $ref instances to {ref}.

This would be a good first issue for newcomers, although preprocessors hook and recursively looping over the dictionary object that adjust the types may be challenging to someone who's not comfortable with that. You can follow the addFontStyles code as an example though:

https://github.com/tokens-studio/sd-transforms/blob/main/src/parsers/add-font-styles.ts
https://github.com/tokens-studio/sd-transforms/blob/main/test/spec/parsers/add-font-styles.spec.ts

**Comment by jorenbroekema** [comment]
At this point I don't think many people are using this old ref style, and given that we have a DTCG spec that tries to standardize, I don't think this library should burden itself with supporting the old way. You can always create a custom preprocessor on your end to handle it though.
